parameters:
  nightly: false

steps:
- checkout: none

- script: /root/scripts/azure-build.sh nightly
  condition: eq('${{ parameters.nightly }}', 'true')
- script: /root/scripts/azure-build.sh
  condition: eq('${{ parameters.nightly }}', 'false')

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: "build_archive"
    targetPath: ./build.tar.gz
